//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsidTest
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> IsCEO { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string Role { get; set; }
        public string ReportsTo { get; set; }

    }
}
