//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsidTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryItem
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> RunTimeMinutes { get; set; }
        public Nullable<bool> IsBorrowable { get; set; }
        public string Borrower { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public string Type { get; set; }
    
        public virtual Category Category { get; set; }

        public void SetAcronymedTitle(string title, string AcronymedTitle)
        {
            Title = $"{ title } ({ AcronymedTitle })";
        }

    }
}
